version: 2

models:

    - name: sales
      description: > 
        One line per product + ordder id each day, from 2021-04-01 to 2021-09-30 included.
        Main sales KPI => margin
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: Id of the order. The orde_id can be displayed on several rows
            tests : 
            - not_null 

          - name: products_id
            description: Id od the product purchased. May have several product_id per order_id
            tests:
              - not_null
                  

          - name: qty

          - name: turnover
            description: turnover per row
            tests:
              - not_null
              

          - name: purchase_cost
            description: cost of one product
            tests:
              - not_null

          - name: margin
            description: turnover / purchase_cost